import { Link } from "react-router-dom";
import { Navbar } from "../../components/layout";
import Footer from "../../components/Footer";

function LegalSection({ title, children }) {
  return (
    <section className="mb-8 last:mb-0">
      <h2 className="text-xl font-semibold text-text-primary m-0 mb-3">{title}</h2>
      <div className="text-sm text-text-secondary leading-relaxed space-y-3">{children}</div>
    </section>
  );
}

function LegalPageShell({ eyebrow, title, subtitle, children, updated }) {
  return (
    <div className="min-h-screen bg-background text-text-primary flex flex-col">
      <Navbar />
      <main className="flex-1">
        <div className="border-b border-border">
          <div className="max-w-[800px] mx-auto px-6 py-12 sm:py-16">
            <p className="text-sm font-semibold text-primary m-0 mb-3 tracking-wide uppercase">
              {eyebrow}
            </p>
            <h1 className="text-3xl sm:text-4xl font-bold text-text-primary m-0 leading-tight">
              {title}
            </h1>
            {subtitle ? (
              <p className="text-base text-text-secondary m-0 mt-3 max-w-[640px]">{subtitle}</p>
            ) : null}
            {updated ? (
              <p className="text-xs text-text-muted m-0 mt-4">Last updated: {updated}</p>
            ) : null}
          </div>
        </div>
        <div className="max-w-[800px] mx-auto px-6 py-10 sm:py-12">{children}</div>
      </main>
      <Footer />
    </div>
  );
}

export function TermsOfServicePage() {
  return (
    <LegalPageShell
      eyebrow="Legal"
      title="Terms of Service"
      subtitle="The agreement between you and Adal AI when you use our platform."
      updated="September 16, 2026"
    >
      <LegalSection title="1. Acceptance of terms">
        <p className="m-0">
          By creating an account or using Adal AI (&quot;the Service&quot;), you agree to these Terms
          of Service. If you do not agree, do not use the Service.
        </p>
      </LegalSection>
      <LegalSection title="2. The service">
        <p className="m-0">
          Adal AI provides legal practice management tools (cases, documents, workspaces, AI
          features) and a marketplace for clients to discover and book verified lawyers. Features
          available to you depend on your role, verification status, and workspace plan.
        </p>
      </LegalSection>
      <LegalSection title="3. Accounts and eligibility">
        <p className="m-0">
          You must provide accurate registration information and keep your credentials secure. You
          are responsible for activity under your account. Lawyers may need additional verification
          before accepting client bookings.
        </p>
      </LegalSection>
      <LegalSection title="4. Acceptable use">
        <p className="m-0">
          You may not misuse the Service, attempt unauthorized access, upload unlawful content, or
          use the platform to harass others. We may suspend accounts that violate these terms.
        </p>
      </LegalSection>
      <LegalSection title="5. Professional responsibility">
        <p className="m-0">
          Adal AI is a software platform, not a law firm. Content generated by AI tools is
          assistive only and does not constitute legal advice. Lawyers remain solely responsible for
          professional judgment, confidentiality, and compliance with applicable bar rules.
        </p>
      </LegalSection>
      <LegalSection title="6. Bookings and payments">
        <p className="m-0">
          Marketplace bookings and any fees are subject to the booking flow and payment terms shown
          at checkout. Disputes should be raised through the in-app dispute process where available.
        </p>
      </LegalSection>
      <LegalSection title="7. Subscriptions">
        <p className="m-0">
          Workspace plans (Base, Max, Firm) and trials are described on our{" "}
          <Link to="/pricing" className="text-primary hover:underline">
            Pricing
          </Link>{" "}
          page. Billing is per workspace unless otherwise stated.
        </p>
      </LegalSection>
      <LegalSection title="8. Termination">
        <p className="m-0">
          You may stop using the Service at any time. We may suspend or terminate access for
          violations of these terms or to protect the platform and its users.
        </p>
      </LegalSection>
      <LegalSection title="9. Contact">
        <p className="m-0">
          Questions about these terms:{" "}
          <a href="mailto:support@adal-ai.com" className="text-primary hover:underline">
            support@adal-ai.com
          </a>
          . See also our{" "}
          <Link to="/privacy" className="text-primary hover:underline">
            Privacy Policy
          </Link>
          .
        </p>
      </LegalSection>
    </LegalPageShell>
  );
}

export function PrivacyPolicyPage() {
  return (
    <LegalPageShell
      eyebrow="Legal"
      title="Privacy Policy"
      subtitle="How Adal AI collects, uses, and protects personal information."
      updated="September 16, 2026"
    >
      <LegalSection title="1. Information we collect">
        <p className="m-0">
          We collect account details (name, email, password), profile and verification information
          for lawyers, booking and payment-related data, workspace and case content you create, and
          technical logs needed to operate and secure the Service.
        </p>
      </LegalSection>
      <LegalSection title="2. How we use information">
        <p className="m-0">
          We use data to provide and improve the Service, process bookings, manage subscriptions,
          send transactional notifications, verify lawyers, prevent fraud, and comply with law.
        </p>
      </LegalSection>
      <LegalSection title="3. Sharing">
        <p className="m-0">
          We share information with service providers who help us operate (hosting, email, payments),
          when required by law, or with your direction (for example, sharing a booking with the other
          party). We do not sell personal information.
        </p>
      </LegalSection>
      <LegalSection title="4. Case and document content">
        <p className="m-0">
          Matter data, notes, and documents are processed to deliver features you enable (including
          optional AI tools). Access is governed by workspace roles and permissions you configure.
        </p>
      </LegalSection>
      <LegalSection title="5. Retention and security">
        <p className="m-0">
          We retain information as long as needed for the purposes above or as required by law. We
          apply administrative and technical safeguards appropriate to the sensitivity of the data.
        </p>
      </LegalSection>
      <LegalSection title="6. Your choices">
        <p className="m-0">
          You may update profile information in settings, request account deletion by contacting
          support, and manage notification preferences where available.
        </p>
      </LegalSection>
      <LegalSection title="7. Cookies">
        <p className="m-0">
          We use cookies and similar technologies as described in our{" "}
          <Link to="/cookies" className="text-primary hover:underline">
            Cookie Policy
          </Link>
          .
        </p>
      </LegalSection>
      <LegalSection title="8. Contact">
        <p className="m-0">
          Privacy requests:{" "}
          <a href="mailto:support@adal-ai.com" className="text-primary hover:underline">
            support@adal-ai.com
          </a>
          .
        </p>
      </LegalSection>
    </LegalPageShell>
  );
}

export function CookiePolicyPage() {
  return (
    <LegalPageShell
      eyebrow="Legal"
      title="Cookie Policy"
      subtitle="How Adal AI uses cookies and similar technologies."
      updated="September 16, 2026"
    >
      <LegalSection title="1. What are cookies">
        <p className="m-0">
          Cookies are small text files stored on your device. We also use local storage and similar
          technologies to keep you signed in and remember preferences such as theme.
        </p>
      </LegalSection>
      <LegalSection title="2. How we use them">
        <p className="m-0">
          Essential cookies enable authentication, security, and core navigation. Preference cookies
          remember settings. Analytics cookies (if enabled) help us understand product usage so we
          can improve the Service.
        </p>
      </LegalSection>
      <LegalSection title="3. Your controls">
        <p className="m-0">
          You can control cookies through your browser settings. Blocking essential cookies may
          prevent sign-in or other core features from working.
        </p>
      </LegalSection>
      <LegalSection title="4. More information">
        <p className="m-0">
          See our{" "}
          <Link to="/privacy" className="text-primary hover:underline">
            Privacy Policy
          </Link>{" "}
          or contact{" "}
          <a href="mailto:support@adal-ai.com" className="text-primary hover:underline">
            support@adal-ai.com
          </a>
          .
        </p>
      </LegalSection>
    </LegalPageShell>
  );
}
